# Generated by Django 3.0.7 on 2020-06-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20200626_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.ManyToManyField(blank=True, to='course.Language'),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.ManyToManyField(blank=True, to='course.Level'),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.ManyToManyField(blank=True, to='course.Subject'),
        ),
    ]
