# Generated by Django 3.0.7 on 2020-06-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20200626_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='language',
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='course',
            name='level',
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='course',
            name='subject',
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.TextField(blank=True, null=True),
        ),
    ]
